##Curve Fitting
曲線あてはめ

### Generalized curve fitting
一般化された曲線あてはめ

Principle:原理

Given a set of data points, find a function $l=f(a)$ which "best-fits" the given points
一連のデータ点が与えられたとき、与えられた点に「最もよく適合する」関数 $l=f(a)$ を見つける。

This function can then be used to estimate values of $l$ at other points
この関数は、その後、他の点での $l$ の値を推定するために使用できます。


Polynomial curve fitting 多項式曲線あてはめ
Suppose, the given data set consists of $n$ data point: $a_{i}$, $l_{i}$
与えられたデータセットが $n$ 個のデータ点 $a_{i}$, $l_{i}$ から成ると仮定します。
And the curve to be fitted to data is an $m^{th}$ order polynomial: $(m+1)<n$
そして、データにあてはめる曲線は $m$ 次の多項式であるとします。

 $(m+1)<n$[cite_start]$l=f(a;x)=x_{0}+x_{1}a+\cdots+x_{m-1}a^{m-1}+x_{m}a^{m}$

 $l=f(a;x)=x_{0}+x_{1}a+\cdots+x_{m-1}a^{m-1}+x_{m}a^{m}$ （多項式の式です）

 The goal of curve fitting is to find the coefficients belonging the "best-fit" curve

 曲線あてはめの目標は、「最もよく適合する」曲線に属する係数を見つけることです

 $\hat{x}=[\begin{matrix}\hat{x}_{0}&\hat{x}_{1}&\cdots&\hat{x}_{m}\end{matrix}]^{T}$ [cite: 33]$\hat{x}=[\begin{matrix}\hat{x}_{0}&\hat{x}_{1}&\cdots&\hat{x}_{m}\end{matrix}]^{T}$ （推定される係数ベクトルです）

In [1]:
import numpy as np

# 仮の観測データ（a: 入力, l: 出力）
a = np.array([1, 2, 3, 4, 5])     # x の値
l = np.array([2.1, 4.0, 5.9, 8.2, 10.1])  # y の値

# 直線モデル f(a) = x0 + x1 * a
A = np.vstack([np.ones(len(a)), a]).T

# 最小二乗解 x = (A^T A)^(-1) A^T l
x_hat = np.linalg.inv(A.T @ A) @ A.T @ l
print("推定された係数:", x_hat)

推定された係数: [4.95492536e-15 2.02000000e+00]


### 最小二乗法を Python に置き換える
<br>


このコードは、与えられたデータ点に対して最小二乗法を用いて直線フィッティングを行うものです。

1. import numpy as np:
-数値計算ライブラリである NumPy をインポートし、np という別名で使用できるようにします。

2. a = np.array([1, 2, 3, 4, 5]):
- 入力データ（x の値）を NumPy 配列 a として定義します。


3. l = np.array([2.1, 4.0, 5.9, 8.2, 10.1]):
- 出力データ（y の値）を NumPy 配列 l として定義します。


4. A = np.vstack([np.ones(len(a)), a]).T:
- これは、直線モデル $l = x_0 + x_1 * a$$l = x_0 + x_1 * a$ の係数 $x_0$$x_0$ と $x_1$$x_1$ を求めるための行列 $A$$A$ を構築しています。
   - np.ones(len(a)) は、a と同じ長さの要素がすべて 1 の配列を作成します。これは、定数項 $x_0$$x_0$ に対応します。
   - np.vstack([...]) は、これらの配列を縦に積み重ねて行列を作成します。
   - .T は、行列を転置します。これにより、各行がデータ点に対応し、各列が係数に対応する行列 A が作成されます。具体的には、A は以下のようになります。
<br>   
[[1. 1. 1. 1. 1.]<br>
 [1. 2. 3. 4. 5.]]
<br>
 を転置して
 <br>

[[1. 1.]<br>
 [1. 2.]<br>
 [1. 3.]<br>
 [1. 4.]<br>
 [1. 5.]]<br>
<br>
 となります。
 <br>

5. x_hat = np.linalg.inv(A.T @ A) @ A.T @ l:
- これは、最小二乗法の公式 $x = (A^T A)^{-1} A^T l$$x = (A^T A)^{-1} A^T l$ を用いて、最適な係数ベクトル $\hat{x} = [x_0, x_1]^T$$\hat{x} = [x_0, x_1]^T$ を計算しています。
   - A.T @ A は、$A$$A$ の転置行列と $A$$A$ の行列積です。
   - np.linalg.inv(...) は、その結果の逆行列を計算します。
   - @ A.T @ l は、逆行列と $A$$A$ の転置行列、そして出力データベクトル $l$$l$ の行列積を計算しており、これが最小二乗解である係数ベクトル $\hat{x}$$\hat{x}$ となります。


6. print("推定された係数:", x_hat): 計算された係数 x_hat を表示します。この例では、x_hat の最初の要素が $x_0$$x_0$（切片）、2 番目の要素が $x_1$$x_1$（傾き）となります。



このコードの実行結果は、与えられたデータ点に最もよくフィットする直線の切片と傾きを示しています。